website/courses/urls.py
from django.urls import path

from courses.views import CoursesView

app_name = "courses"
urlpatterns = [path("<int:year>/<slug:season_slug>/", CoursesView.as_view(), name="lectures")]

website/giphousewebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView, TemplateView

from github_oauth.templatetags.github_tags import url_github_callback


class GitHubLoginRedirectView(RedirectView):
    """Redirect to GitHub login page."""

    permanent = True
    query_string = True
    pattern_name = "login-redirect"

    def get_redirect_url(self, *args, **kwargs):
        """Return the redirect url for GitHub login."""
        return url_github_callback(
            {"request": self.request}, "login", next_url=reverse_lazy("admin:index")
        )  # pragma: no cover


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="home"),
    path("admin/login/", GitHubLoginRedirectView.as_view(), name="login-redirect"),
    path("admin/logout/", RedirectView.as_view(url="/logout", query_string=True), name="logout-redirect"),
    path("admin/", admin.site.urls),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("oauth/", include("github_oauth.urls")),
    path("lectures/", include("courses.urls")),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("for-companies/", TemplateView.as_view(template_name="for-companies.html"), name="for-companies"),
    path("contact/", TemplateView.as_view(template_name="contact.html"), name="contact"),
    path("questionnaires/", include("questionnaires.urls")),
    path("register/", include("registrations.urls")),
    path("projects/", include("projects.urls")),
    path("reservations/", include("room_reservation.urls")),
    path("lectures/", include("lecture_registrations.urls")),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/questionnaires/urls.py
from django.urls import path

from questionnaires.views import OverviewView, QuestionnaireView

app_name = "questionnaires"

urlpatterns = [
    path("", OverviewView.as_view(), name="overview"),
    path("<int:questionnaire>", QuestionnaireView.as_view(), name="questionnaire"),
]

website/questionnaires/forms.py
from django import forms
from django.forms import ValidationError

from questionnaires.models import QuestionnaireSubmission
from questionnaires.widgets import ButtonGroupWidget


class QuestionnaireForm(forms.Form):
    """Dynamic form generating a questionnaires form."""

    def __init__(self, participant, questionnaire, peers, no_peers_warning, check_required=False, *args, **kwargs):
        """Dynamically setup form."""
        super().__init__(*args, **kwargs)

        self.check_required = check_required

        try:
            self.submission = QuestionnaireSubmission.objects.get(
                participant=participant, questionnaire=questionnaire, submitted=False
            )
        except QuestionnaireSubmission.DoesNotExist:
            self.submission = None

        self.participant = participant
        self.questionnaire = questionnaire
        self.questions = questionnaire.question_set.order_by("pk")
        self.peers = peers
        self.no_peers_warning = no_peers_warning

        for question in self.questions:
            if question.about_team_member:
                peers_question = self.peers
            else:
                peers_question = (None,)

            for peer in peers_question:
                self._build_form_field(self.get_field_name(question, peer), question, peer)
                if question.is_closed and question.with_comments:
                    self._build_form_field(
                        self.get_field_name(question, peer, comments=True), question, peer, is_comments=True
                    )

    def clean(self):
        """Validate that the questionnaire is not yet answered."""
        try:
            QuestionnaireSubmission.objects.get(
                participant_id=self.participant.id, questionnaire_id=self.questionnaire.id, submitted=True
            )
        except QuestionnaireSubmission.DoesNotExist:
            pass
        else:
            raise ValidationError("Questionnaire already submitted.", code="invalid")

    def _build_form_field(self, field_name, question, peer=None, is_comments=False):
        if question.is_closed and not is_comments:
            self.fields[field_name] = forms.TypedChoiceField(
                label=question.question,
                widget=ButtonGroupWidget,
                choices=question.get_likert_choices(),
                coerce=int,
                empty_value=None,
            )
        else:
            self.fields[field_name] = forms.CharField(
                label=question.question,
                widget=forms.Textarea(
                    attrs={"rows": 4, "placeholder": ""},
                ),
            )

        if not self.check_required or (question.optional or is_comments):
            # Mark all questions as not required, to allow intermediate saves
            self.fields[field_name].required = False
            self.fields[field_name].widget.is_required = False

        if question.optional or is_comments:
            self.fields[field_name].help_text = "Optional"

        if self.submission:
            # Set the initial value for a field if a submission already exists
            answer = self.submission.answer_set.filter(question=question, peer=peer).first()
            if is_comments:
                self.fields[field_name].initial = answer.answer.comments if answer else None
            else:
                self.fields[field_name].initial = answer.answer.value if answer else None

        if peer is not None:
            self.fields[field_name].peer = f"{peer.get_full_name()}"

        self.fields[field_name].is_comments_field = is_comments

    @staticmethod
    def get_field_name(question, peer=None, comments=False):
        """Generate the name of a field used in the HTML to identify a question."""
        if peer is not None:
            if comments:
                return f"question-{question.pk}-{peer.pk}-comments"
            return f"question-{question.pk}-{peer.pk}"
        if comments:
            return f"question-{question.pk}-comments"
        return f"question-{question.pk}"

website/questionnaires/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from courses.models import Semester

from giphousewebsite.mixins import LoginRequiredMessageMixin

from projects.models import Project

from questionnaires.forms import QuestionnaireForm
from questionnaires.models import Answer, Questionnaire, QuestionnaireSubmission

from registrations.models import Employee, Registration

User: Employee = get_user_model()


class OverviewView(LoginRequiredMessageMixin, TemplateView):
    """List the available questionnaires."""

    template_name = "questionnaires/overview.html"

    def get_context_data(self, **kwargs):
        """Add the current questionnaires and submissions to the context of the view."""
        context = super().get_context_data()

        context["submissions"] = []
        context["open_questionnaires"] = []
        context["questionnaires_in_progress"] = []
        for questionnaire in Questionnaire.objects.current_questionnaires():

            try:
                context["submissions"].append(
                    QuestionnaireSubmission.objects.get(
                        questionnaire=questionnaire, participant=self.request.user, submitted=True
                    )
                )
            except QuestionnaireSubmission.DoesNotExist:
                context["questionnaires_in_progress"].append(questionnaire) if QuestionnaireSubmission.objects.filter(
                    questionnaire=questionnaire, participant=self.request.user, submitted=False
                ).exists() else context["open_questionnaires"].append(questionnaire)

        return context


class QuestionnaireView(LoginRequiredMessageMixin, FormView):
    """A dynamically generated FormView."""

    template_name = "questionnaires/questionnaire.html"
    form_class = QuestionnaireForm

    def get_form_kwargs(self):
        """Add extra information to the form."""
        kwargs = super().get_form_kwargs()

        participant = self.request.user
        kwargs["participant"] = participant

        questionnaire = get_object_or_404(Questionnaire, pk=self.kwargs["questionnaire"])
        if questionnaire.is_closed:
            raise Http404

        kwargs["questionnaire"] = questionnaire

        participant_projects = Project.objects.filter(
            registration__user=participant, semester=Semester.objects.get_or_create_current_semester()
        )
        project_registrations = Registration.objects.filter(projects__in=participant_projects)
        kwargs["peers"] = User.objects.exclude(pk=participant.pk).filter(registration__in=project_registrations)

        kwargs["no_peers_warning"] = (
            questionnaire.question_set.filter(about_team_member=True).exists() and not kwargs["peers"]
        )

        return kwargs

    def form_valid(self, form):
        """Validate the form."""
        if "submit" in self.request.POST:
            # Re-evaluate the form to check required fields
            form_check_required_fields = QuestionnaireForm(**self.get_form_kwargs(), check_required=True)
            if not form_check_required_fields.is_valid():
                form._errors = form_check_required_fields.errors
                return self.form_invalid(form)

            submission, _ = QuestionnaireSubmission.objects.get_or_create(
                questionnaire=form.questionnaire, participant=self.request.user
            )
            submission.submitted = True
            submission.save()
        else:
            submission, _ = QuestionnaireSubmission.objects.get_or_create(
                questionnaire=form.questionnaire, participant=self.request.user
            )
            submission.submitted = False
            submission.save()

        for question in form.questions:

            if question.about_team_member:
                peers = form.peers
            else:
                peers = (None,)

            for peer in peers:
                field_name = QuestionnaireForm.get_field_name(question, peer)
                answer, _ = Answer.objects.get_or_create(submission=submission, peer=peer, question=question)
                answer.answer = form.cleaned_data[field_name]
                if question.with_comments:
                    answer.comments = form.cleaned_data[
                        QuestionnaireForm.get_field_name(question, peer, comments=True)
                    ]

        if submission.submitted:
            messages.success(self.request, "Questionnaire successfully submitted!", extra_tags="success")
            return redirect("home")
        else:
            messages.info(self.request, "Questionnaire saved", extra_tags="info")
            return self.render_to_response(self.get_context_data())

website/questionnaires/templates/questionnaires/overview.html
{% extends 'base.html' %}

{% block title %}
    Overview Questionnaires - {{ block.super }}
{% endblock %}

{% block header_image_container %}
{% endblock %}

{% block content %}
    <div class="col-8">
        <div>
            <h4>Questionnaires</h4>
			{% if open_questionnaires or questionnaires_in_progress %}
				<table class="table">
					<thead>
						<tr>
							<th scope="col">Title</th>
							<th scope="col">Available Until</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
                    {% for questionnaire in questionnaires_in_progress %}
                        <tr>
                            <td>{{ questionnaire.title }}</td>
                            <td>{{ questionnaire.get_until_date|default_if_none:'Closed' }}</td>
                            <td>
                                {% if questionnaire.is_open %}
                                    <a class="btn btn-primary" role="button" href="{% url 'questionnaires:questionnaire' questionnaire.pk %}">Continue</a>
                                {% elif questionnaire.is_late %}
                                    <a class="btn btn-primary" role="button" href="{% url 'questionnaires:questionnaire' questionnaire.pk %}">Continue (Late)</a>
                                {% else %}
                                    <a class="btn btn-primary disabled" role="button" href="#">Continue</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    {% for questionnaire in open_questionnaires %}
							<tr>
								<td>{{ questionnaire.title }}</td>
								<td>{{ questionnaire.get_until_date|default_if_none:'Closed' }}</td>
								<td>
									{% if questionnaire.is_open %}
										<a class="btn btn-primary" role="button" href="{% url 'questionnaires:questionnaire' questionnaire.pk %}">Start</a>
									{% elif questionnaire.is_late %}
										<a class="btn btn-primary" role="button" href="{% url 'questionnaires:questionnaire' questionnaire.pk %}">Start Late</a>
									{% else %}
										<a class="btn btn-primary disabled" role="button" href="#">Start</a>
									{% endif %}
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			{% else %}
				<p>
					No questionnaires available.
				</p>
			{% endif %}
        </div>

		{% if submissions %}
        <div>
            <h4>Submissions</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Title</th>
                        <th scope="col">Submission Date</th>
                        <th scope="col">On Time</th>
                    </tr>
                </thead>
                <tbody>
                    {% for submission in submissions %}
                        <tr>
                            <td>{{ submission.questionnaire.title }}</td>
                            <td>{{ submission.created }}</td>
                            <td>
                                {% if submission.late %}
                                    <i class="fas fa-times"></i>
                                {% else %}
                                    <i class="fas fa-check"></i>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
		{% endif %}
    </div>
{% endblock %}

website/questionnaires/templates/questionnaires/questionnaire.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}
    {{form.questionnaire.title}} - Questionnaire - {{ block.super }}
{% endblock %}

{% block header_image_container %}
{% endblock %}

{% block content %}
  {% if form.no_peers_warning %}
    <p class="text-danger">This questionnaire contains questions about your team members, but you are either not in a project, or your project has no other peers.</p>
  {% endif %}
	<h1 class="mt-2">{{form.questionnaire.title}}</h1>
    {% bootstrap_form_errors form %}
    <form method="post" class="row">
        {% csrf_token %}
        {% for field in form %}
			{% ifchanged field.label %}
				<div class="col-12">
					<hr/>
					<h4>{{ field.label }}</h4>
				</div>
			{% endifchanged %}
			<div class="col-2">
                {% if field.field.is_comments_field %}
                    <p class="font-italic">Comments</p>
                {% else %}
                    <p class="fw-bold"> {{ field.field.peer }}</p>
                {% endif %}
			</div>
			<div class="col-10 col-lg-10">
				{% bootstrap_field field show_label=False %}
            </div>
        {% endfor %}
		<div class="col-12 mb-5">
            {% bootstrap_button "Save" name="save" value="save" button_type="submit" button_class="btn-primary" %}
            {% bootstrap_button "Submit" name="submit" value="submit" button_type="submit" button_class="btn-secondary" %}
        </div>
    </form>
{% endblock %}