website/courses/urls.py
from django.urls import path

from courses.views import CoursesView

app_name = "courses"
urlpatterns = [path("<int:year>/<slug:season_slug>/", CoursesView.as_view(), name="lectures")]

website/giphousewebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView, TemplateView

from github_oauth.templatetags.github_tags import url_github_callback


class GitHubLoginRedirectView(RedirectView):
    """Redirect to GitHub login page."""

    permanent = True
    query_string = True
    pattern_name = "login-redirect"

    def get_redirect_url(self, *args, **kwargs):
        """Return the redirect url for GitHub login."""
        return url_github_callback(
            {"request": self.request}, "login", next_url=reverse_lazy("admin:index")
        )  # pragma: no cover


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="home"),
    path("admin/login/", GitHubLoginRedirectView.as_view(), name="login-redirect"),
    path("admin/logout/", RedirectView.as_view(url="/logout", query_string=True), name="logout-redirect"),
    path("admin/", admin.site.urls),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("oauth/", include("github_oauth.urls")),
    path("lectures/", include("courses.urls")),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("for-companies/", TemplateView.as_view(template_name="for-companies.html"), name="for-companies"),
    path("contact/", TemplateView.as_view(template_name="contact.html"), name="contact"),
    path("questionnaires/", include("questionnaires.urls")),
    path("register/", include("registrations.urls")),
    path("projects/", include("projects.urls")),
    path("reservations/", include("room_reservation.urls")),
    path("lectures/", include("lecture_registrations.urls")),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/lecture_registrations/urls.py
from django.urls import path

from lecture_registrations.views import LectureRegistrationView
from lecture_registrations.views import LectureUnregistrationView

app_name = "lecture_registrations"

urlpatterns = [
    path("<int:pk>/register", LectureRegistrationView.as_view(), name="register_for_lecture"),
    path("<int:pk>/unregister", LectureUnregistrationView.as_view(), name="unregister_for_lecture"),
]

website/courses/models.py
from django.core.validators import FileExtensionValidator, MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone


def current_year():
    """Wrap a call to timezone returning the current year."""
    return timezone.now().year


def max_value_current_year(value):
    """Validate value, limit modelinput to current_year, call current_year to keep validator from changing per year."""
    return MaxValueValidator(current_year() + 1)(value)


class CourseManager(models.Manager):
    """Manager for the Course model."""

    def se(self):
        """Create Software Engineering course."""
        return self.get(name="Software Engineering")

    def sdm(self):
        """Create System Development Management course."""
        return self.get(name="System Development Management")

    def sde(self):
        """Create Software Development Entrepreneurship course."""
        return self.get(name="Software Development Entrepreneurship")


class Course(models.Model):
    """Model to represent course."""

    name = models.CharField(max_length=50)

    objects = CourseManager()

    def __str__(self):
        """Return name of course."""
        return f"{self.name}"


class SemesterManager(models.Manager):
    """Manager for the Semester model."""

    def get_first_semester_with_open_registration(self):
        """Get the first semester with an open registration."""
        return self.filter(registration_start__lte=timezone.now(), registration_end__gte=timezone.now()).first()

    def get_or_create_current_semester(self):
        """
        Return the current semester based on the current time.

        Given that there is no deterministic way to determine the start of the semesters,
        we start the semesters at reasonable dates that are close to the actual start dates.

        The spring semester starts on the 14 days before the monday in the last week of january.
        The fall semester starts on september 1st.

        August is considered spring semester for simplicity.
        """
        jan31 = timezone.now().replace(
            year=timezone.now().year, month=1, day=31, hour=0, minute=0, second=0, microsecond=0
        )

        spring_semester_start = jan31 - timezone.timedelta(days=jan31.weekday()) - timezone.timedelta(days=14)

        fall_semester_start = timezone.now().replace(
            year=timezone.now().year, month=9, day=1, hour=0, minute=0, second=0, microsecond=0
        )

        if timezone.now() < spring_semester_start:
            return self.get_or_create(year=timezone.now().year - 1, season=Semester.FALL)[0]

        elif spring_semester_start <= timezone.now() < fall_semester_start:
            return self.get_or_create(year=timezone.now().year, season=Semester.SPRING)[0]

        # In the case fall_semester_start <= timezone.now()
        # In other words, if the start of the fall semester has passed.
        return self.get_or_create(year=current_year(), season=Semester.FALL)[0]


class Semester(models.Model):
    """Model for a semester (a year and a season)."""

    class Meta:
        """
        The semesters are ordered chronologically in descending order.

        For example:
        - Fall 2019 comes before spring 2019.
        - Spring 2019 comes before fall 2018.
        """

        ordering = ["-year", "-season"]
        unique_together = [["year", "season"]]

    SPRING = 0
    FALL = 1
    CHOICES = ((SPRING, "Spring"), (FALL, "Fall"))

    year = models.IntegerField(validators=[MinValueValidator(2008), max_value_current_year])
    season = models.PositiveSmallIntegerField(choices=CHOICES, default=SPRING)

    registration_start = models.DateTimeField(
        blank=True, null=True, help_text="This must be filled in to open the registration."
    )
    registration_end = models.DateTimeField(
        blank=True, null=True, help_text="This must be filled in to open the registration."
    )

    objects = SemesterManager()

    @staticmethod
    def slug_to_season(slug_string):
        """Return season id when given a slug."""
        if slug_string.lower() == "spring":
            return Semester.SPRING

        elif slug_string.lower() == "fall":
            return Semester.FALL

    def __str__(self):
        """Return semester season and year as string."""
        return f"{self.get_season_display()} {self.year}"


def get_slides_filename(instance, filename):
    """
    Generate slides filename.

    :param instance: Lecture instance
    :param filename: name of uploaded file
    :return: Name of file to save.
    """
    return (
        f"courses/slides/"
        f"{ instance.course }-"
        f"{ instance.title }-"
        f'{ instance.date.strftime("%d-%b-%Y") }'
        f".pdf"
    )


class Lecture(models.Model):
    """Lecture model."""

    class Meta:
        """
        Meta class for Lecture model.

        Describing that course and title should be unique together.
        """

        unique_together = (("course", "title", "semester"),)

    date = models.DateField()

    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)

    title = models.CharField(max_length=50)

    description = models.TextField(blank=True, null=True)

    teacher = models.CharField(max_length=50, blank=True, null=True)

    location = models.CharField(max_length=50, blank=True, null=True)

    slides = models.FileField(
        upload_to=get_slides_filename, validators=[FileExtensionValidator(["pdf"])], blank=True, null=True
    )

    capacity = models.PositiveSmallIntegerField(null=True, blank=True)

    register_until = models.DateTimeField(null=True, blank=True)

    @property
    def can_register(self):
        """Return True if users should be able to (un)register for this lecture at this point in time."""
        return not (self.registration_required and self.register_until and timezone.now() > self.register_until)

    @property
    def registration_required(self):
        """Is registration for this lecture enabled."""
        return self.register_until is not None

    @property
    def capacity_reached(self):
        """Is the registration capacity for this lecture reached."""
        return self.capacity is not None and self.lectureregistration_set.count() >= self.capacity

    @property
    def registered_users(self):
        """Return a list of employees that are registered for this lecture."""
        return self.lectureregistration_set.values_list("employee", flat=True)

    def __str__(self):
        """Return value of Lecture and date object."""
        return f"{ self.course } ({ self.date })"

website/courses/forms.py
from django import forms
from django.utils import timezone

from courses.models import Semester


def year_choices():
    """Return years from 2008 to next year."""
    return [(r, r) for r in range(2008, timezone.now().year + 2)]


class AdminSemesterForm(forms.ModelForm):
    """Semester Object form with typed choices for the year."""

    year = forms.TypedChoiceField(coerce=int, choices=year_choices, initial=timezone.now().year)

    class Meta:
        """Link SemesterForm to Semester model."""

        model = Semester
        exclude = []

website/courses/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from courses.models import Course, Lecture, Semester


class CoursesView(TemplateView):
    """View to display the lectures for a course."""

    template_name = "courses/index.html"

    def get_context_data(self, **kwargs):
        """
        Overridden get_context_data method to add a list of courses and lectures to the template.

        :return: New context.
        """
        context = super(CoursesView, self).get_context_data(**kwargs)

        context["lecture_semester"] = get_object_or_404(
            Semester, year=self.kwargs["year"], season=Semester.slug_to_season(self.kwargs["season_slug"])
        )

        courses = {}
        for course_name in Course.objects.values_list("name", flat=True):
            courses[course_name] = Lecture.objects.filter(
                course__name=course_name,
                semester__year=self.kwargs["year"],
                semester__season=Semester.slug_to_season(self.kwargs["season_slug"]),
            ).order_by("date")

        context["courses"] = courses.items()
        return context

website/courses/templates/courses/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block title %}Lectures - {{ block.super }}{% endblock %}
{% block content %}

    {% for course, lectures in courses %}
        <div class="course">
            <h2 class="section-title">{{ course }} - {{ lecture_semester }}</h2>

            {% if not lectures %}
                <h5>No lectures found</h5>
            {% else %}
                {% if lectures|length > 1 %}
                    <div class="accordion" id="lectures-accordion" >
                {% endif %}
                        {% for lecture in lectures %}
                            <div class="card">
                                <div class="card-header bg-primary" id="heading-lecture-{{ lecture.pk }}">
                                    <h2 class="card-header-text left-and-right mb-0">
                                        <button class="btn btn-link text-white" type="button" data-bs-toggle="collapse" data-bs-target="#lecture-{{ lecture.pk }}" aria-expanded="false" aria-controls="lecture-{{ lecture.pk }}">
                                            {{ lecture.date }} - {{ lecture.title }}
                                        </button>
                                        <button class="btn btn-link text-white" type="button" data-bs-toggle="collapse" data-bs-target="#lecture-{{ lecture.pk }}" aria-expanded="false" aria-controls="lecture-{{ lecture.pk }}">
                                            <i class="fas fa-bars"></i>
                                        </button>
                                    </h2>
                                </div>

                                <div class="collapse" id="lecture-{{ lecture.pk }}" aria-labelledby="heading-lecture-{{ lecture.pk }}">
                                    <div class="card-body">
                                        <div class="table-responsive align-baseline">
                                            <table class="table table-borderless table-sm">
                                                <tbody>
                                                    <tr>
                                                        <th scope="row">Teacher</th>
                                                        <td>{{ lecture.teacher|default:"-" }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">Location</th>
                                                        <td>{{ lecture.location|default:"-" }}</td>
                                                    </tr>
                                                    {% if lecture.registration_required %}
                                                        <tr>
                                                            <th scope="row">Registrations</th>
                                                            <td>
                                                                {{ lecture.lectureregistration_set.count }} / {{ lecture.capacity|default_if_none:"∞" }} {% if request.user.pk in lecture.registered_users %}<span class="ms-4">You are registered</span>{% endif %}
                                                                {% if request.user.is_authenticated and lecture.can_register %}
                                                                    {% if request.user.pk in lecture.registered_users %}
                                                                        <form name="lecture-registration-form" class="mt-2" action="{% url 'lecture_registrations:unregister_for_lecture' lecture.pk %}" method="post">
                                                                            {% csrf_token %}
                                                                            {% bootstrap_button "Unregister" %}
                                                                        </form>
                                                                    {% endif %}
                                                                    {% if not lecture.capacity_reached and request.user.pk not in lecture.registered_users %}
                                                                        <form name="lecture-registration-form" class="mt-2" action="{% url 'lecture_registrations:register_for_lecture' lecture.pk %}" method="post">
                                                                            {% csrf_token %}
                                                                            {% bootstrap_button "Register" %}
                                                                        </form>
                                                                    {% endif %}
                                                                {% endif %}
                                                            </td>
                                                        </tr>
                                                    {% endif %}
                                                    <tr>
                                                        <td colspan="2">
                                                            {% if lecture.slides %}
                                                                <a class="btn btn-primary" href="{{ lecture.slides.url }}">Download Slides</a>
                                                            {% else %}
                                                                No slides available
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>

                                            {% if lecture.description %}
                                                {{ lecture.description|linebreaks }}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                {% if lectures|length > 1 %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}