website/courses/urls.py
from django.urls import path

from courses.views import CoursesView

app_name = "courses"
urlpatterns = [path("<int:year>/<slug:season_slug>/", CoursesView.as_view(), name="lectures")]

website/giphousewebsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path, reverse_lazy
from django.views.generic import RedirectView, TemplateView

from github_oauth.templatetags.github_tags import url_github_callback


class GitHubLoginRedirectView(RedirectView):
    """Redirect to GitHub login page."""

    permanent = True
    query_string = True
    pattern_name = "login-redirect"

    def get_redirect_url(self, *args, **kwargs):
        """Return the redirect url for GitHub login."""
        return url_github_callback(
            {"request": self.request}, "login", next_url=reverse_lazy("admin:index")
        )  # pragma: no cover


urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="home"),
    path("admin/login/", GitHubLoginRedirectView.as_view(), name="login-redirect"),
    path("admin/logout/", RedirectView.as_view(url="/logout", query_string=True), name="logout-redirect"),
    path("admin/", admin.site.urls),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("oauth/", include("github_oauth.urls")),
    path("lectures/", include("courses.urls")),
    path("about/", TemplateView.as_view(template_name="about.html"), name="about"),
    path("for-companies/", TemplateView.as_view(template_name="for-companies.html"), name="for-companies"),
    path("contact/", TemplateView.as_view(template_name="contact.html"), name="contact"),
    path("questionnaires/", include("questionnaires.urls")),
    path("register/", include("registrations.urls")),
    path("projects/", include("projects.urls")),
    path("reservations/", include("room_reservation.urls")),
    path("lectures/", include("lecture_registrations.urls")),
    path("tinymce/", include("tinymce.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/projects/urls.py
from django.urls import path

from projects.views import ProjectsView

app_name = "projects"
urlpatterns = [path("<int:year>/<slug:season_slug>/", ProjectsView.as_view(), name="projects")]

website/giphousewebsite/views.py
from django.shortcuts import get_list_or_404
from registrations.models import Project
from django.views.generic import TemplateView


class ProjectsView(TemplateView):
    """View to display the projects for a year."""

    template_name = 'projects.html'

    def get_context_data(self, year, season, **kwargs):
        """
        Overridden get_context_data method to add a list of projects to the template.

        :return: New context.
        """
        context = super(ProjectsView, self).get_context_data(**kwargs)
        context['projects'] = get_list_or_404(
            Project.objects.filter(semester__year=year).filter(semester__season=season))
        return context

website/giphousewebsite/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About - {{ block.super }}{% endblock %}
{% block content %}
    <h3>What is GiPHouse?</h3>
    <p>GiPHouse is a virtual software company of the Radboud University Nijmegen, which has already been active for more than 25 years. GiPHouse is entirely run by students and is divided into two parts, which run independently from each other in the spring and fall semesters.</p>
    <p>For students, working for GiPHouse is a perfect opportunity to get some real-life experience as a software developer, as a project manager or with creating a start-up. Besides developing the software, we also expect students to spend time on team meetings, meetings with their customers, writing documentation and other important project-related work. Collaboration in a professional context is therefore a key-aspect of the GiPHouse courses.</p>

    <p>During every first half of the calendar year (spring semester), GiPHouse develops software for paying customers. These projects are completely developed by students, who get study credits for successfully participating in the courses that are linked to GiPHouse. Working on these projects is the main focus of the courses. Project teams usually consist of six to eight engineers (bachelor students) and one to three project managers (master students).</p>
    <p>During the second half of the calendar year (fall semester), a master's course is given about beginning a start-up company. In this course, students are tasked with developing software around a central theme. This software will hopefully be the start of a real start-up, which could go on even after the course is finished.</p>

    <ul class="nav nav-pills my-5 nav-justified" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
          <button class="nav-link active" id="spring-semester-tab" data-bs-toggle="pill" data-bs-target="#pills-spring-semester" type="button" role="tab" aria-controls="pills-spring-semester" aria-selected="true"><h3>Spring semester</h3>(Software Engineering & System Development Management)</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="fall-semester-tab" data-bs-toggle="pill" data-bs-target="#pills-fall-semester" type="button" role="tab" aria-controls="pills-fall-semester" aria-selected="false"><h3>Fall semester</h3>(Software Development Entrepreneurship)</button>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-spring-semester" role="tabpanel" aria-labelledby="spring-semester-tab" tabindex="0">
          <div class="row">
              <div class="col-12 col-lg-6">
                  <h4>Software Engineering <a href="https://www.ru.nl/courseguides/science/vm/osirislinks/ibi/nwi-ibi001/" target="_blank"><span class="badge rounded-pill bg-primary mx-3">NWI-IBI001</span></a></h4>
                  <p>The Software Engineering (SE) course is a course for bachelor students of the Computing Science programme. In this course, most students will get their real-life experience as a software developer, working for an actual customer. During the course, students work in teams of about 6 to 8 software engineers, and two or three project managers. Learning objectives are:</p>
                  <ul>
                      <li>agile software development</li>
                      <li>Scrum methodology</li>
                      <li>working together as a team in a professional context</li>
                      <li>developing high-quality code, using design principles and software patterns</li>
                      <li>systematic testing techniques</li>
                  </ul>
                  <p>The estimated workload for this course is 168 hours (6 ec). This includes lectures, project meetings, meetings with the customer, and working on the project itself.</p>
              </div>
              <div class="col-12 col-lg-6">
                  <h4>System Development Management <a href="https://www.ru.nl/courseguides/science/vm/osirislinks/imc/nwi-imc021/" target="_blank"><span class="badge rounded-pill bg-primary mx-3">NWI-IMC021</span></a></h4>
                  <p>The System Development Management (SDM) course is a course for master's students of the Information Sciences programme. In this course, students learn how to be a manager of a software development project team, working for an actual customer. Teams consist of two or three managers, leading about 6 to 8 software engineers. Learning objectives are:</p>
                  <ul>
                      <li>agile software development</li>
                      <li>Scrum methodology</li>
                      <li>pro-active communication with different stakeholders</li>
                      <li>managing project risks</li>
                      <li>showing leadership and guarding team synergy</li>
                      <li>using modern project management tools</li>
                  </ul>
                  <p>The estimated workload for this course is 168 hours (6 ec). This includes lectures, project meetings, meetings with the customer, and working on the project itself.</p>
              </div>
          </div>
          <div class="row">
              <div class="col-12">
                  <h3 class="mt-3">The project</h3>
                  <p>After course registration, students receive project descriptions for all projects of the year. Those descriptions contain a small summary of the client, the idea of the project and possibly any specific skills that can be relevant for the project. Students can express their preferences for projects they want to work on, as well as team members they want to collaborate with. Based on these preferences, students are assigned to teams.</p>
                  <p>At the first kick-off day of the course, students will meet their teams and have a first meeting with their client. Then a brief start-up period follows in which teams can get their background knowledge up to par and try to get a clearer overview of what the project is about. The students are usually free to choose their favourite programming language and platform, baring client wishes.</p>
                  <p>After this, teams follow scrum methodology and work in sprints, where each sprint finishes with a working product. Besides software development, students also give intermediate presentations and write a project plan, sprint plans and reviews, et cetera.</p>
                  <p>At the end of the semester, the customer has to judge the quality of the product and the team-customer collaboration. The final grade for the course is an average of the customer judgement and a judgement of the teachers that involves both the quality of the end-product, the intermediate documentation of the process and collaboration within the team.</p>
                  <p>Teams are expected to work physically together on-campus for at least one daypart per week (preferably more), supplement with individual, hybrid or online work for the rest of the course's workload. It is not required to work during the hours scheduled by the university.</p>
              </div>
          </div>
          <div class="row">
              <h3 class="mt-3">GiPHouse structure</h3>
              <p>Within GiPHouse we simulate an actual corporate experience. We will try to explain the structure of the organization below</p>
              <div class="col-12 col-lg-6">
                  <h5>Supervisory Board (teachers)</h5>
                  <p>Although the teachers do not have a concrete function within the organization, they are crucial for the courses surrounding GiPHouse. The teachers are responsible for the course material and the grading of the students.</p>
                  <h5>Executive Board (directors)</h5>
                  <p>GiPHouse is run by a board of student assistants, also called <em>directors</em>. They are responsible for the smooth day-to-day running of the company and it's projects. There are different roles they fulfill. </p>
                  <ul>
                      <li><strong>CEO</strong>: responsible for coordination within the executive board.</li>
                      <li><strong>Secretary</strong>: responsible for all communication and archiving.</li>
                      <li><strong>Facilities</strong>: responsible for any practical matters, like managing building access, project room management or organizing small GiPHouse events.</li>
                      <li><strong>IT</strong>: manages the GiPHouse's technical infrastructure.</li>
                      <li><strong>Sales</strong>: does project acquisition and maintains contact with customers in the period the project is not actually running.</li>
                      <li><strong>Human resources</strong>: team composition and interventions in case of issues.</li>
                      <li><strong>Quality assurance</strong>: assesses, evaluates and reports progress of project teams. Team managers primarily report to their assigned QA director.</li>
                  </ul>
                  <h5>Managers (SDM students) </h5>
                  <p>Every team has two or three managers. The managers are responsible for the documentation for the directors, ensuring the expectations of the clients are managed correctly and steering the agile development process.</p>
                  <h5>Engineers (SE students) </h5>
                  <p>Engineers are responsible for the actual code that is delivered at the end of the project. Aside from creating the features the client desires, they are also responsible for documentation and the testing of the code.</p>
              </div>
              <div class="col-12 col-lg-6">
                  <img src="{% static "img/organogram.png" %}" alt="Organogram" class="img-fluid mt-4">
                  <h4 class="mt-5">Issues</h4>
                  <p>For employees, the general approach to take when a problem arises is to contact the person that is one layer within the organization above you. For engineers, this means you should initially always try to contact your manager first. If that does not work out, you can contact the executive board. If the problem is not solved by the executive board, you can contact the teachers.</p>
              </div>
        </div>
      </div>
      <div class="tab-pane fade" id="pills-fall-semester" role="tabpanel" aria-labelledby="fall-semester-tab" tabindex="0">
          <h4>Software Development Entrepreneurship <a href="https://www.ru.nl/courseguides/science/vm/osirislinks/nwi-imi004/" target="_blank"><span class="badge rounded-pill bg-primary mx-3">NWI-IMI004</span></a></h4>
          <p>In the Software Development Entrepreneurship (SDE) course, students will be starting their own small business around a software product. Students work in small teams of about 3 to 5 students. Learning objectives are:</p>
          <ul>
              <li>doing market research and pursuing outreach</li>
              <li>setting up a business model and creating a business plan</li>
              <li>developing a realistic software product that is ready for market</li>
          </ul>
          The estimated workload for this course is 168 hours (6 ec).
      </div>
    </div>
{% endblock %}

website/giphousewebsite/templates/base.html
{% load static sass_tags django_bootstrap5 menu %}
<!DOCTYPE html>
<html lang="en">
<head>

    <title>
        {% block title %}GiPHouse{% endblock %}
    </title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% sass_src 'scss/main.scss' %}" type="text/css">

    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon/favicon.ico' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon/favicon-32x32.png' %}"/>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="512x512" href="{% static 'img/favicon/android-chrome-512x512.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'img/favicon/android-chrome-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon/favicon-16x16.png' %}">
    <!-- build commit: {{ COMMIT_HASH }} -->
</head>
<body>
{% render_main_menu %}

<header id="page-header">
    {% block header_image_container %}
        <img src="{% block header_image %}{% static "img/huygens.jpg" %}{% endblock header_image %}" class="w-100" alt="header"/>
    {% endblock header_image_container %}
</header>
<div class="container pt-4 pb-5">
    {% bootstrap_messages %}

    {% block content %}
    {% endblock %}
</div>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

website/giphousewebsite/templates/contact.html
{% extends 'base.html' %}
{% block title %}Contact - {{ block.super }}{% endblock %}
{% block content %}
    <h1>Contact Information</h1>
    <p>If you want more information or are interested in doing a project with GiPHouse, you can email us.</p>

    <div class="row">
        <div class="col-lg-5">
            <h4>Address </h4>
            <address>
                <ul class="list-unstyled">
                    <li class="fw-bold">GiPHouse</li>
                    <li>Toernooiveld 200, Room M1.0.13</li>
                    <li>6525 EC, Nijmegen</li>
                    <li>The Netherlands</li>
                    <li>Email: <a href="mailto:directors@giphouse.nl">directors@giphouse.nl</a>
                </ul>
            </address>
        </div>

        <div class="col-lg-5">
            <h4>Social Links</h4>
            <ul class="list-unstyled">
                <li><i class="fab fa-github"></i> <a href="https://github.com/Giphouse" class="btn-social btn-outline">Github Organization</a></li>
                <li><i class="fab fa-github"></i> <a href="https://github.com/Giphouse/Website" class="btn-social btn-outline">This website is open source!</a></li>
                <li><i class="fab fa-twitter"></i> <a href="https://twitter.com/giphouse" class="btn-social btn-outline">Twitter</a></li>
                <li><i class="fab fa-linkedin"></i> <a href="https://nl.linkedin.com/in/giphouse" class="btn-social btn-outline">LinkedIn</a></li>
            </ul>

        </div>
    </div>

{% endblock %}

website/giphousewebsite/templates/for-companies.html
{% extends 'base.html' %}
{% block title %}For Companies - {{ block.super }}{% endblock %}
{% block content %}
    <h3>Running a project at GiPHouse</h3>
    <p>GiPHouse is a unique student-run software development company linked to two courses at the Radboud University’s Computing Science and Information Sciences programmes. During the spring semester, students from both bachelor and master’s programmes get their first experience working on a software development project for a 'real' customer, and meanwhile learn technical and soft skills (collaboration in teams, agile principles, etc).</p>
    <p>We're always looking for new potential clients who want to run a project at GiPHouse. In the past, all different kinds of project have run at GiPHouse, from all kinds of different clients: from small start-ups, to large (inter)national organizations.</p>
    <p>For most organizations, this is a unique opportunity to get a group of enthusiastic students to work on a project for low cost, for which the organization does not have the time to invest in too much. From our experience, projects that involve developing prototypes, proof of concepts or simple tools, are most successful.</p>
    <div class="row">
        <p>Here are some examples of projects that have run at GiPHouse in the past:</p>
        <div class="col-12 col-md-6">
            <ul>
                <li><strong>NS Engineer app</strong>: creating a proof-of-concept self-service app for NS maintenance engineers to remotely send commands to gates at train stations.</li>
                <li><strong>RU WeblectureControl</strong>: development of a unified central control system for a large variety of internet-connected AV control systems.</li>
                <li><strong>Thirona Performance Dashboard</strong>: building a dashboard for statistics from image analysis software pipelines.</li>
            </ul>
        </div>
        <div class="col-12 col-md-6">
            <ul>
                <li><strong>InfoSupport Deppy</strong>: further development of a tool that provides insights into dependencies of a software project.</li>
                <li><strong>Gears2VA</strong>: building a prototype of voice assistant implementation in an information system.</li>
            </ul>
        </div>
    </div>
    <hr class="my-5">
    <div class="row">
        <h3>I would like to run a project with GiPHouse</h3>
        <p>Our projects are carried out during the second semester (usually around February - June). During the first semester (September - December) the GiPHouse management will look for suitable projects for the students to work on. They can be contacted on <a href="mailto:sales@giphouse.nl">sales@giphouse.nl</a>. During this period it's possible to contact us to see whether there is room for your project(s). In the first contact, we will check with you whether the project is suitable for the course.</p>
        <div class="col-12 col-lg-6">
            <h5>Project description</h5>
            <p>If your project is suitable, we will ask you to write a project description. This description will be used by students to express their preference for certain projects. This description should contain the following (please also check the example project description):</p>
            <ul>
                <li>About one paragraph about the client (company), what is it that you do?</li>
                <li>Information on the project, what is the project about? What is the purpose of the project?</li>
                <li>Necessary skills, what programming language or frameworks will be used? (optional)</li>
                <li>Contact information, who are you? How can the project group reach you?</li>
            </ul>
            <p>After an agreement is reached on the project description, the contracts can be signed and the project is ready for the spring semester.</p>

            <h5>Costs</h5>
            <p>Running a project within GiPHouse (spring semester) is possible for only &euro;450,-. This is a fixed price and the money will mainly be used for project-related costs like development tools and servers, printing, travelling and administrative costs. Note that this money is not used to pay students for their work: they get a reward for their work in the form of study credits.</p>

            <h5>Intellectual property and non-disclosure</h5>
            <p>The intellectual property of the project is always owned by the client, and not by GiPHouse or the students working on it.</p>
            <p>For educational purposes, students are expected to present their progress to the teachers to the other students of the courses. We also need to keep a copy of the students work. This means that it is not possible to enforce a non-disclosure agreement that would not allow this to happen. Moreover, we cannot enforce our students to sign a non-disclosure agreement when working on your project. If your project really requires an NDA, the exact details need to be discussed upfront. In our experience however, this has never been a deal-breaker and we've always found a solution that is satisfactory for all parties.</p>
        </div>
        <div class="col-12 col-lg-6">
            <div class="card text-bg-light mb-3">
              <div class="card-header">
                  <h4><em>Example project description:</em><br>GiPHouse GSuite+GitHub sync</h4>
              </div>
              <div class="card-body">
                <h5 class="card-title">GiPHouse</h5>
                <p class="card-text">GiPHouse is a virtual software company completely run by students. For more than 25 years now, GiPHouse has provided a platform in which real projects for real companies can be created. Furthermore, it has been a learning platform for students who want to get real life software development experience.  </p>

                <h5 class="card-title">The project</h5>
                <p class="card-text">At the moment, GiPHouse uses several different systems (e.g. G Suite and Github) to manage and monitor its projects and administration. The goal of this project is to create a more efficient method to administer the projects and student data. At this moment we have a system running on <a href="https://giphouse.nl">giphouse.nl</a> but we still have to do a lot of manual work in other systems. We would like to automate as many of those tasks as possible.</p>
                <p class="card-text">With the registration of students we already gain a lot of information of users (e.g. Github accounts, mail addresses). Right now we have to manually create repositories for the teams and add every user manually, we would like to do this automatically once we have everyone divided in teams. The same goes for functionalities of G Suite that we use. Depending on how long this takes, we would also like to look into ways to fairly divide the students into teams using our system.</p>
                <p class="card-text">In this project there will be a big focus on code quality. At the moment, the website has a high code quality and if we integrate this project into our live environment we seek the same level of quality. You can take a look into the current website here: <a href="https://github.com/Giphouse/Website">https://github.com/Giphouse/Website</a>.</p>

                <h5 class="card-title">Skills</h5>
                <p class="card-text">Experience with Django (a popular web framework in Python) is a plus.</p>

                <h5 class="card-title">Contact Information</h5>
                <p class="card-text">Name: A B<br>
                    E-mail: a@b.com<br>
                    Phone/WhatsApp/Telegram: 06-12345678
                </p>
              </div>
            </div>
        </div>
    </div>

    <hr class="my-5">

    <h3>While the project is running</h3>
    <p>There are some things that you should be aware of when you would like to have a project with GiPHouse, these will be explained below. If you have any questions feel free to contact us (<a href="mailto:sales@giphouse.nl">sales@giphouse.nl</a>). Please make sure you have read the bullets below.</p>

    <div class="row">
        <div class="col-12 col-md-6">
            <ul>
                <li>We expect you to be available at the start of the project for an initial kick-off meeting. We will let you know when this will be.</li>
                <li>During the project we expect you to be available for the team. There is not a set window for this, but you are expected to be available for questions/discussion at least once every two weeks. The exact frequency and moments for this can be discussed with the team of students.</li>
                <li>At the end of the project we have some questions that we hope you can answer. These questions help the teachers with the grading of the students. Topics that are covered are the quality of the product, your satisfaction with the product and the way of working, communication, and questions on your collaboration.</li>
                <li>The students are expected to reach an agreement with you on how the product should be handed over to you. We urge you to think about this in advance to ensure you can actually use the product after the team is done working on it. Note that after the project is over, GiPHouse or the students cannot deliver any support anymore.</li>
                <li>GiPHouse will provide students with their development environment. This means that students have GitHub services and AWS servers available to them to make sure they can properly work on their product. In case your project requires a team to run an existing product on these services, it is important that this product is stable and secure. It is also possible that you provide this infrastructure yourself.</li>
            </ul>
        </div>
        <div class="col-12 col-md-6">
            <ul>
                <li>While the students are expected to deliver an end product that you are satisfied with, they also have to work on several aspects of software development in order to be able to pass the course. This means that students still have to work on aspects that may seem superfluous, like tests, maintainability, and documentation.</li>
                <li>GiPHouse is working with students and not with paid professionals. This means that we cannot guarantee that every project will be completely up to par with the customers' wishes. By emphasising good communication between students and the customers, we try to give the projects a successful conclusion. We know from experience that most projects are finished or mostly finished and customers are predominantly satisfied with us.</li>
                <li>While nearly every project is considered a great success by our clients, it's always possible that something is not going the right way. If there are any problems along the way (e.g. you feel that the final product will not be satisfactory), please contact the management as soon as possible.</li>
            </ul>
        </div>
    </div>
{% endblock %}

website/giphousewebsite/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-md">
            <h1>GiPHouse</h1>
            <p>GiPHouse is a unique student-run company that develops software and practices entrepreneurship at the Radboud University.</p>
        </div>
    </div>
    {% if current_projects %}
        <h2>Currently running projects</h2>
        <div class="row">
            {% for project in current_projects %}
                <div class="col-12 col-md-6 col-lg-4">
                    <a class="no-underline"
                       href="{% url 'projects:projects' current_semester.year current_semester.get_season_display|lower %}#{{ project.id }}">
                        <div class="card my-2">
                            {% if project.client.logo %}
                                <div class="client-logo">
                                    <img class="card-img-top img-fluid"
                                                              src="{{ project.client.logo.url }}"
                                                              alt="logo {{ project.client.name }}">
                                </div>
                            {% else %}
                                <div class="client-logo client-logo-placeholder"></div>
                            {% endif %}
                            <div class="card-body">
                                <h4 class="card-title">{{ project.name }}</h4>
                                <h6 class="card-subtitle text-muted">
                                    {% if project.client %}
                                        By {{ project.client.name }}
                                    {% else %}
                                        Current project
                                    {% endif %}
                                </h6>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}